/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/universe/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Universe Stats
         * @description Universe composition as of a date. Non-survivors are counted, never
         *     excluded — they stay in the universe permanently (invariant 2).
         */
        get: operations["universe_stats_universe_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ranking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ranking
         * @description Active companies we KNOW haven't inflected (stage_max <= 2), ranked by
         *     revenue momentum, plus any company with a hand-verified catalyst estimate
         *     regardless of stage range.
         *
         *     Ordering: fresh rows first — estimate-backed by nearest p50, then momentum
         *     by streak — with stale rows below all of them, most recently observed
         *     first. "Stale" means the latest observed quarter ended more than ~18
         *     months before `as_of`; such a company is still listed and filing, so the
         *     row is demoted and labelled rather than dropped.
         *
         *     `catalyst` is null when no estimate is on file. That is a real answer —
         *     the absence of an estimate is never filled in with a guess.
         */
        get: operations["ranking_ranking_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Transitions
         * @description Detected stage crossings across the whole universe, most recent first.
         *
         *     The default 2 -> 3 (first revenue -> inflection) is the signal this
         *     project exists to find. Non-survivors are included: excluding them is
         *     precisely the survivorship bias invariant 2 forbids.
         */
        get: operations["transitions_transitions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Companies */
        get: operations["list_companies_companies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{cik}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Company Detail
         * @description Everything known about one company as of a date, in one round trip:
         *     status history, fact coverage, estimates, and the classified quarter
         *     series the ranking is derived from.
         */
        get: operations["company_detail_companies__cik__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{cik}/quarters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Company Quarters
         * @description Discrete per-quarter values, before classification. A missing quarter
         *     is a real gap — a period quarantined into concept_conflicts is absent
         *     here rather than estimated.
         */
        get: operations["company_quarters_companies__cik__quarters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{cik}/stages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Company Stages
         * @description Stage assignment per observed quarter. Computed fresh and never
         *     persisted — stage_assignments is a rebuildable cache, and an HTTP read
         *     has no business writing to it.
         */
        get: operations["company_stages_companies__cik__stages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CompanyDetail */
        CompanyDetail: {
            /** Cik */
            cik: string;
            /** Name */
            name: string;
            /** As Of */
            as_of: string;
            /** Status */
            status: string;
            /** Status Date */
            status_date?: string | null;
            /** Status Events */
            status_events: components["schemas"]["StatusEvent"][];
            /** Fact Count */
            fact_count: number;
            /** Concepts */
            concepts: string[];
            /** Units */
            units: string[];
            /** First Period End */
            first_period_end?: string | null;
            /** Latest Period End */
            latest_period_end?: string | null;
            /** Latest Knowledge Date */
            latest_knowledge_date?: string | null;
            /**
             * Conflict Count
             * @description Alias disagreements quarantined out of `facts` for this company. Non-zero is a caveat on the series below, not a bug.
             */
            conflict_count: number;
            /** Catalyst Estimates */
            catalyst_estimates: components["schemas"]["EstimateRange"][];
            /** Buildout Estimates */
            buildout_estimates: components["schemas"]["EstimateRange"][];
            /** Series */
            series: components["schemas"]["SeriesPoint"][];
            /** Transitions 2 To 3 */
            transitions_2_to_3: components["schemas"]["Transition"][];
        };
        /** CompanyListResponse */
        CompanyListResponse: {
            /** As Of */
            as_of: string;
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Companies */
            companies: components["schemas"]["CompanySummary"][];
        };
        /** CompanySummary */
        CompanySummary: {
            /** Cik */
            cik: string;
            /** Name */
            name: string;
            /**
             * Status
             * @description 'active', or the latest recorded status event.
             */
            status: string;
            /** Status Date */
            status_date?: string | null;
            /** Fact Count */
            fact_count: number;
            /** Latest Period End */
            latest_period_end?: string | null;
        };
        /**
         * EstimateRange
         * @description A dated milestone as a distribution, never a single date (invariant 3).
         */
        EstimateRange: {
            /** As Of Date */
            as_of_date: string;
            /** P10 Date */
            p10_date: string;
            /** P50 Date */
            p50_date: string;
            /** P90 Date */
            p90_date: string;
            /**
             * Basis
             * @description Filing-level reasoning behind the range.
             */
            basis?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Db Path */
            db_path: string;
            /** Companies */
            companies: number;
            /** Facts */
            facts: number;
            /** Latest Knowledge Date */
            latest_knowledge_date?: string | null;
        };
        /** QuarterPoint */
        QuarterPoint: {
            /** Period Start */
            period_start?: string | null;
            /** Period End */
            period_end: string;
            /** Value */
            value: number;
            /** Corroborated */
            corroborated: boolean;
        };
        /** RankEntry */
        RankEntry: {
            /** Cik */
            cik: string;
            /** Name */
            name: string;
            /**
             * Stage
             * @description stage_min, or 'min-max' when the range is undetermined.
             */
            stage: string;
            /**
             * As Of
             * @description Period end of the latest quarter observed for this company.
             */
            as_of: string;
            /**
             * Stale
             * @description Latest observation older than 546 days.
             */
            stale: boolean;
            /** Age Days */
            age_days: number;
            /**
             * Streak
             * @description Consecutive quarter-over-quarter revenue increases.
             */
            streak: number;
            /**
             * Latest Quarterly Revenue
             * @description Unit is whatever the filer reported in; mostly USD, some EUR/CHF/CAD/GBP. Not currency-normalized.
             */
            latest_quarterly_revenue: number;
            /** @description Time to first revenue. Null means no estimate on file — never a guess. */
            catalyst?: components["schemas"]["EstimateRange"] | null;
            /** @description Time to full buildout. */
            buildout?: components["schemas"]["EstimateRange"] | null;
        };
        /** RankingResponse */
        RankingResponse: {
            /** As Of */
            as_of: string;
            /**
             * Total
             * @description Entries matching the filters, before pagination.
             */
            total: number;
            /** Fresh */
            fresh: number;
            /** Stale */
            stale: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Entries */
            entries: components["schemas"]["RankEntry"][];
        };
        /** SeriesPoint */
        SeriesPoint: {
            /** Period End */
            period_end: string;
            /** Value */
            value: number;
            /**
             * Corroborated
             * @description Another alias tag agreed within tolerance. Confidence signal, not a correctness guarantee.
             */
            corroborated: boolean;
            /** Streak */
            streak: number;
            /** Stage */
            stage: string;
            /** Stage Min */
            stage_min: number;
            /** Stage Max */
            stage_max: number;
            /**
             * Basis
             * @description Which classifier rule fired.
             */
            basis: string;
        };
        /** StatusEvent */
        StatusEvent: {
            /** Effective Date */
            effective_date: string;
            /** Status */
            status: string;
        };
        /** Transition */
        Transition: {
            /** Cik */
            cik: string;
            /** Name */
            name: string;
            /** Period End */
            period_end: string;
            /** From Stage */
            from_stage: number;
            /** To Stage */
            to_stage: number;
        };
        /** UniverseStats */
        UniverseStats: {
            /** As Of */
            as_of: string;
            /** Companies */
            companies: number;
            /** Active */
            active: number;
            /** Inactive */
            inactive: number;
            /** By Status */
            by_status: {
                [key: string]: number;
            };
            /** Status Events */
            status_events: number;
            /** Facts */
            facts: number;
            /** Companies With Facts */
            companies_with_facts: number;
            /** Concept Conflicts */
            concept_conflicts: number;
            /** Catalyst Estimates */
            catalyst_estimates: number;
            /** Buildout Estimates */
            buildout_estimates: number;
            /** Earliest Knowledge Date */
            earliest_knowledge_date?: string | null;
            /** Latest Knowledge Date */
            latest_knowledge_date?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    universe_stats_universe_stats_get: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniverseStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ranking_ranking_get: {
        parameters: {
            query?: {
                /** @description Simulated present. Omit for today. */
                as_of?: string | null;
                /** @description Stale rows are demoted, never dropped. */
                include_stale?: boolean;
                /** @description Only rows with a real catalyst estimate on file. */
                estimates_only?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transitions_transitions_get: {
        parameters: {
            query?: {
                as_of?: string | null;
                from_stage?: number;
                to_stage?: number;
                /** @description Only transitions at or after this period end. */
                since?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transition"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_companies_companies_get: {
        parameters: {
            query?: {
                as_of?: string | null;
                /** @description Case-insensitive substring of name or CIK. */
                q?: string | null;
                status?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    company_detail_companies__cik__get: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path: {
                cik: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    company_quarters_companies__cik__quarters_get: {
        parameters: {
            query?: {
                as_of?: string | null;
                concept?: string;
            };
            header?: never;
            path: {
                cik: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuarterPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    company_stages_companies__cik__stages_get: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path: {
                cik: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
